#!/usr/bin/env bash
# Generated by amplifier-bundle-dev-machine — do not edit directly
# =============================================================================
# dev-machine-watchdog.sh -- Health check for the dev machine (every 15 min)
#
# Checks:
#   1. Container is running
#   2. Container isn't stuck (CPU = 0% for too long with no new commits)
#   3. SSH agent is alive (needed for push step)
#   4. No zombie/crashed state
#
# Actions:
#   - Restarts container if unhealthy
#   - Restarts SSH agent if socket is dead
#   - Logs everything to dev-machine-watchdog.log
# =============================================================================
set -euo pipefail

PROJECT_DIR="{{project_dir}}"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.dev-machine.yaml"
LOG_FILE="$PROJECT_DIR/dev-machine-watchdog.log"
COMMIT_MARKER="$PROJECT_DIR/.watchdog-last-commit"
HEARTBEAT_FILE="$PROJECT_DIR/.dev-machine-heartbeat"
HEARTBEAT_MAX_AGE=3600   # 60 min -- entrypoint is alive if heartbeat is fresher

log() {
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] $*" >> "$LOG_FILE"
}

log "--- watchdog check start ---"

cd "$PROJECT_DIR"

# ── 1. Is the container running? ─────────────────────────────────────────────
CONTAINER_STATUS=$(docker compose -f "$COMPOSE_FILE" ps --format json 2>/dev/null | python3 -c "
import sys, json
try:
    data = json.loads(sys.stdin.read())
    # docker compose v2 returns a single object or list
    if isinstance(data, list):
        data = data[0] if data else {}
    print(data.get('State', 'unknown'))
except:
    print('unknown')
" 2>/dev/null || echo "unknown")

if [ "$CONTAINER_STATUS" != "running" ]; then
    log "RESTART: container not running (state: $CONTAINER_STATUS)"
    docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true
    docker compose -f "$COMPOSE_FILE" up -d dev-machine 2>> "$LOG_FILE"
    log "Container restarted"
    exit 0
fi

log "Container is running"

# ── 2. Is the SSH agent alive? (needed for git push step) ────────────────────
if [ -z "${SSH_AUTH_SOCK:-}" ] || [ ! -S "${SSH_AUTH_SOCK:-/nonexistent}" ]; then
    log "WARN: SSH_AUTH_SOCK not set or socket missing ($SSH_AUTH_SOCK)"
    log "  Push step will fail gracefully until agent is restored"
    # Don't restart -- the container works fine, just push is degraded
else
    AGENT_OK=$(ssh-add -l 2>/dev/null && echo "yes" || echo "no")
    if [ "$AGENT_OK" = "no" ]; then
        log "WARN: SSH agent socket exists but has no keys loaded"
    else
        log "SSH agent healthy"
    fi
fi

# ── 3. Is the container making progress? ─────────────────────────────────────
CURRENT_HEAD=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
LAST_KNOWN=""
if [ -f "$COMMIT_MARKER" ]; then
    LAST_KNOWN=$(cat "$COMMIT_MARKER")
fi

if [ "$CURRENT_HEAD" != "$LAST_KNOWN" ]; then
    log "Progress detected: HEAD moved to $CURRENT_HEAD"
    echo "$CURRENT_HEAD" > "$COMMIT_MARKER"
else
    # HEAD hasn't moved since last check -- is the container actually working?
    CPU=$(docker stats --no-stream --format '{{.CPUPerc}}' {{container_name}} 2>/dev/null | tr -d '%' || echo "0")
    # Truncate to integer for comparison
    CPU_INT=${CPU%%.*}
    CPU_INT=${CPU_INT:-0}

    if [ "$CPU_INT" -lt 1 ]; then
        # 0% CPU and no commits -- check how many consecutive zero checks
        ZERO_FILE="$PROJECT_DIR/.watchdog-zero-count"
        ZERO_COUNT=0
        if [ -f "$ZERO_FILE" ]; then
            ZERO_COUNT=$(cat "$ZERO_FILE")
        fi
        ZERO_COUNT=$((ZERO_COUNT + 1))
        echo "$ZERO_COUNT" > "$ZERO_FILE"

        if [ "$ZERO_COUNT" -ge 4 ]; then
            # 4 consecutive checks (60 min) with no progress and 0% CPU.
            # BUT: the entrypoint may be alive and managing its own Cloudflare
            # backoff.  Check the heartbeat file before restarting -- if the
            # entrypoint touched it recently, it's alive and we must NOT
            # interfere with its backoff strategy.
            heartbeat_stale=true
            if [ -f "$HEARTBEAT_FILE" ]; then
                heartbeat_age=$(( $(date +%s) - $(stat -c %Y "$HEARTBEAT_FILE") ))
                if [ "$heartbeat_age" -lt "$HEARTBEAT_MAX_AGE" ]; then
                    heartbeat_stale=false
                    log "SKIP RESTART: entrypoint heartbeat is fresh (${heartbeat_age}s ago, threshold ${HEARTBEAT_MAX_AGE}s). Process is alive, likely in Cloudflare backoff."
                else
                    log "Heartbeat file is stale (${heartbeat_age}s ago, threshold ${HEARTBEAT_MAX_AGE}s)"
                fi
            else
                log "No heartbeat file found -- entrypoint may predate heartbeat support"
            fi

            if [ "$heartbeat_stale" = true ]; then
                log "RESTART: container idle for $ZERO_COUNT consecutive checks (${ZERO_COUNT}x15min) with no new commits (heartbeat stale or missing)"
                docker compose -f "$COMPOSE_FILE" down 2>> "$LOG_FILE"
                sleep 5
                docker compose -f "$COMPOSE_FILE" up -d dev-machine 2>> "$LOG_FILE"
                echo "0" > "$ZERO_FILE"
                log "Container restarted after idle detection"
            fi
            # If heartbeat is fresh: don't restart, don't reset ZERO_COUNT.
            # This way, if the heartbeat DOES go stale, restart triggers
            # immediately on the next check instead of waiting another 4 cycles.
        else
            log "WARN: no progress and 0%% CPU (check $ZERO_COUNT of 4 before restart)"
        fi
    else
        # CPU is active, just no commits yet this hour -- that's fine
        log "No new commits but CPU at ${CPU}%% -- container is working"
        echo "0" > "$PROJECT_DIR/.watchdog-zero-count" 2>/dev/null
    fi
fi

# ── 4. Log summary stats ──────────────────────────────────────────────────────
MEM=$(docker stats --no-stream --format '{{.MemUsage}}' {{container_name}} 2>/dev/null || echo "unknown")
UNPUSHED=$(git rev-list --count origin/master..HEAD 2>/dev/null || echo "?")
log "Stats: CPU=${CPU:-?}%, MEM=$MEM, unpushed=$UNPUSHED, HEAD=$CURRENT_HEAD"

log "--- watchdog check end ---"
