#!/usr/bin/env bash
# Generated by amplifier-bundle-dev-machine — do not edit directly
# =============================================================================
# Dev Machine Health Monitor
# Runs every 10 minutes via cron. Detects failure patterns and logs alerts.
# Unlike the watchdog (which restarts), this DIAGNOSES and REPORTS.
# =============================================================================

PROJECT_DIR="{{project_dir}}"
MONITOR_LOG="$PROJECT_DIR/dev-machine-monitor.log"
CONTAINER="{{container_name}}"
MAX_LOG_LINES=500

log() {
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] $*" >> "$MONITOR_LOG"
}

# Rotate log if too large
if [ -f "$MONITOR_LOG" ] && [ "$(wc -l < "$MONITOR_LOG")" -gt "$MAX_LOG_LINES" ]; then
    tail -200 "$MONITOR_LOG" > "$MONITOR_LOG.tmp"
    mv "$MONITOR_LOG.tmp" "$MONITOR_LOG"
fi

log "--- monitor check ---"

# 1. Is container running?
container_status=$(docker inspect -f '{{.State.Status}}' "$CONTAINER" 2>/dev/null || echo "missing")
if [ "$container_status" != "running" ]; then
    log "ALERT: Container not running (status: $container_status)"
    exit 0
fi

# 2. Get current stats
cpu=$(docker stats "$CONTAINER" --no-stream --format '{{.CPUPerc}}' 2>/dev/null || echo "?")
mem=$(docker stats "$CONTAINER" --no-stream --format '{{.MemUsage}}' 2>/dev/null || echo "?")
head_commit=$(cd "$PROJECT_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "?")
unpushed=$(cd "$PROJECT_DIR" && git rev-list --count @{u}..HEAD 2>/dev/null || echo "?")

# 3. Check for silent recipe loop (the 514-attempt pattern)
# Container logs show attempt number — if it's climbing fast with no commits, we're looping.
last_attempt=$(docker logs "$CONTAINER" --tail 50 2>&1 | grep -oP 'attempt \K\d+' | tail -1)
recipe_fail_count=$(docker logs "$CONTAINER" --tail 100 2>&1 | grep -c "Recipe execution failed" || true)

# 4. Check heartbeat freshness
heartbeat_age="n/a"
if [ -f "$PROJECT_DIR/.dev-machine-heartbeat" ]; then
    heartbeat_age=$(( $(date +%s) - $(stat -c %Y "$PROJECT_DIR/.dev-machine-heartbeat") ))
fi

# 5. Check if HEAD has moved since last monitor check
LAST_HEAD_FILE="$PROJECT_DIR/.monitor-last-head"
last_head=$(cat "$LAST_HEAD_FILE" 2>/dev/null || echo "")
head_moved="no"
if [ "$head_commit" != "$last_head" ] && [ -n "$last_head" ]; then
    head_moved="yes"
fi
echo "$head_commit" > "$LAST_HEAD_FILE"

# 6. Check for stale blockers in STATE.yaml
has_blockers="no"
if grep -q "description:" "$PROJECT_DIR/STATE.yaml" 2>/dev/null; then
    blocker_section=$(sed -n '/^blockers:/,/^[a-z]/p' "$PROJECT_DIR/STATE.yaml" 2>/dev/null)
    if echo "$blocker_section" | grep -q "description:"; then
        has_blockers="yes"
    fi
fi

# 7. Check unpushed commit count — alert if accumulating
push_alert=""
if [ "$unpushed" != "?" ] && [ "$unpushed" -gt 20 ]; then
    push_alert=" ALERT:unpushed>20"
fi

# Log status line
log "STATUS: cpu=$cpu mem=$mem head=$head_commit unpushed=$unpushed moved=$head_moved attempt=$last_attempt recipe_fails=$recipe_fail_count heartbeat_age=${heartbeat_age}s blockers=$has_blockers$push_alert"

# 8. Detect specific failure patterns
# Pattern A: Silent recipe loop (high attempt count + recipe failures + no head movement)
if [ "$recipe_fail_count" -gt 5 ] && [ "$head_moved" = "no" ]; then
    log "ALERT: SILENT RECIPE LOOP detected ($recipe_fail_count failures in recent logs, HEAD not moving)"
    log "ACTION: Check 'docker logs $CONTAINER --tail 30' for the failing step"
fi

# Pattern B: Cloudflare block (0% CPU + heartbeat fresh = entrypoint backing off)
if [ "$cpu" = "0.00%" ] && [ "$heartbeat_age" != "n/a" ] && [ "$heartbeat_age" -lt 3600 ]; then
    log "INFO: Entrypoint alive (heartbeat ${heartbeat_age}s ago) but 0% CPU — likely CF backoff"
fi

# Pattern C: Stale blockers preventing work
if [ "$has_blockers" = "yes" ]; then
    log "ALERT: STATE.yaml has active blockers — machine may be unable to start sessions"
fi

# Pattern D: Dead entrypoint (stale heartbeat + 0% CPU)
if [ "$cpu" = "0.00%" ] && [ "$heartbeat_age" != "n/a" ] && [ "$heartbeat_age" -gt 3600 ]; then
    log "ALERT: Entrypoint appears dead (heartbeat ${heartbeat_age}s stale, 0% CPU)"
fi

# Pattern E: Unpushed commits piling up
if [ -n "$push_alert" ]; then
    log "ALERT: $unpushed unpushed commits — push may be failing"
fi

log "--- monitor check end ---"
