#!/usr/bin/env bash
# Generated by amplifier-bundle-dev-machine — do not edit directly
# =============================================================================
# Dev Machine Health Monitor
# Runs every 10 minutes via cron. Detects failure patterns, auto-remediates
# common issues (permission healing, orphaned work, stale STATE.yaml, auto-push),
# and logs results.
# NOTE: No set -euo pipefail — a monitor that dies on errors is worse than useless.
# All errors are handled explicitly with || true and 2>/dev/null guards.
# =============================================================================

PROJECT_DIR="{{project_dir}}"
MONITOR_LOG="$PROJECT_DIR/dev-machine-monitor.log"
CONTAINER="{{container_name}}"
IMAGE_NAME="{{image_name}}"
BUILD_COMMAND="{{build_command}}"
MAX_LOG_LINES=500

log() {
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] $*" >> "$MONITOR_LOG"
}

# -- Log rotation --------------------------------------------------------------
if [ -f "$MONITOR_LOG" ] && [ "$(wc -l < "$MONITOR_LOG")" -gt "$MAX_LOG_LINES" ]; then
    tail -200 "$MONITOR_LOG" > "$MONITOR_LOG.tmp"
    mv "$MONITOR_LOG.tmp" "$MONITOR_LOG"
fi

log "--- monitor check ---"

# -- Permission self-healing ---------------------------------------------------
# Docker can create files owned by the container user. Fix ownership so the host
# cron user can operate on these files. Uses the container image to chown (it
# has the right perms to write those files in the first place).

# Heal monitor log
if [ -f "$MONITOR_LOG" ] && [ ! -w "$MONITOR_LOG" ]; then
    docker run --rm -v "$PROJECT_DIR:$PROJECT_DIR" -w "$PROJECT_DIR" \
        --entrypoint bash "$IMAGE_NAME" \
        -c "chown $(id -u):$(id -g) $MONITOR_LOG" 2>/dev/null || true
    log "HEALED: monitor log ownership"
fi

# Heal .git/objects (Docker commits can create root-owned objects)
ROOT_OBJECTS=$(find "$PROJECT_DIR/.git/objects" -not -user "$(whoami)" 2>/dev/null | head -1)
if [ -n "$ROOT_OBJECTS" ]; then
    docker run --rm -v "$PROJECT_DIR:$PROJECT_DIR" -w "$PROJECT_DIR" \
        --entrypoint bash "$IMAGE_NAME" \
        -c "chown -R $(id -u):$(id -g) .git/" 2>/dev/null || true
    log "HEALED: .git ownership"
fi

# -- Container status ----------------------------------------------------------
container_status=$(docker inspect -f '{{.State.Status}}' "$CONTAINER" 2>/dev/null || echo "missing")

# -- Auto-commit orphaned work -------------------------------------------------
# If the container stopped with uncommitted changes, save the work before we
# potentially exit. This prevents data loss on crash/restart cycles.
cd "$PROJECT_DIR" 2>/dev/null || true
DIRTY=$(git status --porcelain 2>/dev/null | head -1)
if [ -n "$DIRTY" ] && [ "$container_status" != "running" ]; then
    # Heal source file ownership first so git can stage everything
    for dir in src tests specs docs; do
        if [ -d "$PROJECT_DIR/$dir" ]; then
            ROOT_SRC=$(find "$PROJECT_DIR/$dir" -not -user "$(whoami)" 2>/dev/null | head -1)
            if [ -n "$ROOT_SRC" ]; then
                docker run --rm -v "$PROJECT_DIR:$PROJECT_DIR" -w "$PROJECT_DIR" \
                    --entrypoint bash "$IMAGE_NAME" \
                    -c "chown -R $(id -u):$(id -g) $dir/" 2>/dev/null || true
            fi
        fi
    done
    git add -A 2>/dev/null || true
    git commit -m "chore: auto-save orphaned work (monitor recovery)" 2>/dev/null || true
    log "AUTO-COMMIT: saved orphaned work from stopped container"
fi

# -- STATE.yaml-aware status ---------------------------------------------------
# Parse STATE.yaml for feature progress and blocker counts. Also resets any
# features stuck in 'in-progress' when the container is down (stale state).
if [ -f "$PROJECT_DIR/STATE.yaml" ]; then
    _state_vars=$(python3 -c "
import yaml, sys
try:
    state = yaml.safe_load(open('$PROJECT_DIR/STATE.yaml'))
    features = state.get('features', {})
    remaining = sum(1 for f in features.values() if isinstance(f, dict) and f.get('status') in ('ready', 'in-progress', 'blocked'))
    blockers = len(state.get('blockers', []))
    in_progress = [k for k, v in features.items() if isinstance(v, dict) and v.get('status') == 'in-progress']
    print('REMAINING=' + str(remaining))
    print('BLOCKERS=' + str(blockers))
    print('IN_PROGRESS=' + str(len(in_progress)))
except Exception:
    print('REMAINING=?')
    print('BLOCKERS=?')
    print('IN_PROGRESS=?')
" 2>/dev/null) || true
    eval "${_state_vars:-REMAINING=?}" 2>/dev/null || true
    REMAINING="${REMAINING:-?}"
    BLOCKERS="${BLOCKERS:-?}"
    IN_PROGRESS="${IN_PROGRESS:-?}"
    log "STATE: remaining=$REMAINING blockers=$BLOCKERS in_progress=$IN_PROGRESS"

    # Reset stale in-progress features if the container is down
    if [ "$container_status" != "running" ] && [ "$IN_PROGRESS" != "?" ] && [ "$IN_PROGRESS" -gt 0 ] 2>/dev/null; then
        python3 -c "
import yaml
state = yaml.safe_load(open('$PROJECT_DIR/STATE.yaml'))
changed = False
for k, v in state.get('features', {}).items():
    if isinstance(v, dict) and v.get('status') == 'in-progress':
        v['status'] = 'ready'
        changed = True
if changed:
    with open('$PROJECT_DIR/STATE.yaml', 'w') as f:
        yaml.dump(state, f, default_flow_style=False, sort_keys=False)
" 2>/dev/null && log "HEALED: reset stale in-progress features to ready"
    fi
fi

# -- Blocker detection ---------------------------------------------------------
# Check for active entries under the blockers: key in STATE.yaml
has_blockers="no"
if [ -f "$PROJECT_DIR/STATE.yaml" ]; then
    blocker_section=$(sed -n '/^blockers:/,/^[a-z]/p' "$PROJECT_DIR/STATE.yaml" 2>/dev/null)
    if echo "$blocker_section" | grep -q "description:"; then
        has_blockers="yes"
    fi
fi

# -- Exit early if container is not running ------------------------------------
# Cleanup above (orphan commit, STATE.yaml reset) already ran. Nothing further
# is useful without a live container.
if [ "$container_status" != "running" ]; then
    log "ALERT: Container not running (status: $container_status)"
    log "--- monitor check end ---"
    exit 0
fi

# -- Current stats -------------------------------------------------------------
cpu=$(docker stats "$CONTAINER" --no-stream --format '{{.CPUPerc}}' 2>/dev/null || echo "?")
mem=$(docker stats "$CONTAINER" --no-stream --format '{{.MemUsage}}' 2>/dev/null || echo "?")
head_commit=$(cd "$PROJECT_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "?")
unpushed=$(cd "$PROJECT_DIR" && git rev-list --count @{u}..HEAD 2>/dev/null || echo "?")

# -- Silent recipe loop detection ----------------------------------------------
# Container logs show attempt number — if it's climbing fast with no commits,
# we're in a loop.
last_attempt=$(docker logs "$CONTAINER" --tail 50 2>&1 | grep -oP 'attempt \K\d+' | tail -1)
recipe_fail_count=$(docker logs "$CONTAINER" --tail 100 2>&1 | grep -c "Recipe execution failed" || true)

# -- Heartbeat freshness -------------------------------------------------------
heartbeat_age="n/a"
if [ -f "$PROJECT_DIR/.dev-machine-heartbeat" ]; then
    heartbeat_age=$(( $(date +%s) - $(stat -c %Y "$PROJECT_DIR/.dev-machine-heartbeat") ))
fi

# -- HEAD movement tracking ----------------------------------------------------
LAST_HEAD_FILE="$PROJECT_DIR/.monitor-last-head"
last_head=$(cat "$LAST_HEAD_FILE" 2>/dev/null || echo "")
head_moved="no"
if [ "$head_commit" != "$last_head" ] && [ -n "$last_head" ]; then
    head_moved="yes"
fi
echo "$head_commit" > "$LAST_HEAD_FILE"

# -- Unpushed commit annotation ------------------------------------------------
push_alert=""
if [ "$unpushed" != "?" ] && [ "$unpushed" -gt 10 ]; then
    push_alert=" ALERT:unpushed>10"
fi

# -- Status line ---------------------------------------------------------------
log "STATUS: cpu=$cpu mem=$mem head=$head_commit unpushed=$unpushed moved=$head_moved attempt=$last_attempt recipe_fails=$recipe_fail_count heartbeat_age=${heartbeat_age}s blockers=$has_blockers$push_alert"

# ==============================================================================
# Pattern detections + auto-remediation
# ==============================================================================

# Pattern A: Silent recipe loop (high failure count + HEAD not moving)
if [ "$recipe_fail_count" -gt 5 ] && [ "$head_moved" = "no" ]; then
    log "ALERT: SILENT RECIPE LOOP detected ($recipe_fail_count failures in recent logs, HEAD not moving)"
    log "ACTION: Check 'docker logs $CONTAINER --tail 30' for the failing step"
fi

# Pattern B: Cloudflare backoff (0% CPU but heartbeat is fresh)
if [ "$cpu" = "0.00%" ] && [ "$heartbeat_age" != "n/a" ] && [ "$heartbeat_age" -lt 3600 ]; then
    log "INFO: Entrypoint alive (heartbeat ${heartbeat_age}s ago) but 0% CPU — likely CF backoff"
fi

# Pattern C: Stale blockers — verify build blockers are still valid
# If the blocker description mentions build/type tooling, run the build to check
# whether it's genuinely still broken. Auto-clear if it passes.
if [ "$has_blockers" = "yes" ]; then
    blocker_desc=$(sed -n '/^blockers:/,/^[a-z]/p' "$PROJECT_DIR/STATE.yaml" 2>/dev/null | grep "description:" | head -1)
    if echo "$blocker_desc" | grep -qiE "build|typescript|type.?check|pnpm|npm|compile"; then
        log "VERIFY: Build-related blocker detected. Running build to verify..."
        build_output=$(docker exec "$CONTAINER" bash -c "cd $PROJECT_DIR && $BUILD_COMMAND" 2>&1)
        build_exit=$?
        if [ $build_exit -eq 0 ] || echo "$build_output" | grep -q "0 error"; then
            log "AUTO-FIX: Build passes. Clearing stale blocker from STATE.yaml"
            python3 -c "
import yaml
state = yaml.safe_load(open('$PROJECT_DIR/STATE.yaml'))
state['blockers'] = []
with open('$PROJECT_DIR/STATE.yaml', 'w') as f:
    yaml.dump(state, f, default_flow_style=False, sort_keys=False)
" 2>/dev/null || true
        else
            log "ALERT: Build-related blocker is real. Build still fails."
        fi
    else
        log "ALERT: STATE.yaml has active blockers (not build-related) — machine may need human attention"
    fi
fi

# Pattern D: Dead entrypoint (stale heartbeat + 0% CPU)
if [ "$cpu" = "0.00%" ] && [ "$heartbeat_age" != "n/a" ] && [ "$heartbeat_age" -gt 3600 ]; then
    log "ALERT: Entrypoint appears dead (heartbeat ${heartbeat_age}s stale, 0% CPU)"
fi

# Pattern E: Unpushed commits — auto-push if threshold exceeded
# Stash any local dirt, rebase on remote, push, then restore.
if [ "$unpushed" != "?" ] && [ "$unpushed" -gt 10 ]; then
    log "AUTO-FIX: $unpushed unpushed commits. Pushing..."
    cd "$PROJECT_DIR" 2>/dev/null || true
    git stash 2>/dev/null || true
    git pull --rebase 2>/dev/null || true
    if git push 2>/dev/null; then
        NEW_UNPUSHED=$(git rev-list --count @{u}..HEAD 2>/dev/null || echo "?")
        log "AUTO-FIX: Push successful. $NEW_UNPUSHED commits remaining."
    else
        log "AUTO-FIX: Push FAILED. SSH agent may be dead or no network."
    fi
    git stash pop 2>/dev/null || true
fi

log "--- monitor check end ---"
