#!/usr/bin/env bash
# Generated by amplifier-bundle-dev-machine — do not edit directly
# =============================================================================
# Container entrypoint: seed config, install deps, then run command with retries.
#
# The retry loop makes the dev machine resilient to transient LLM provider
# errors (overloaded_error, rate limits, network blips). On failure the
# recipe is restarted after a backoff delay -- STATE.yaml ensures it picks
# up where it left off.
#
# Cloudflare handling: Before each attempt, a pre-flight check pings the
# Anthropic API. If Cloudflare returns a managed challenge (403 + "Just a
# moment..."), we wait with a long backoff instead of launching and crashing.
# Quick crashes (< 120s) also trigger CF-aware longer backoff.
# =============================================================================

set -euo pipefail

AMPLIFIER_DIR="$HOME/.amplifier"
MAX_BACKOFF=300          # 5 minutes ceiling (normal errors)
CF_BACKOFF={{cf_backoff}}           # default 900 = 15 minutes (Cloudflare challenge detected)
INITIAL_BACKOFF=30       # start at 30 seconds
SUCCESS_RESET=600        # if a run lasts > 10 min, reset backoff (it was working)
CF_CRASH_THRESHOLD=120   # if crash < 2 min, assume Cloudflare
INTER_SESSION_COOLDOWN={{inter_session_cooldown}}  # default 60s pause between successful sessions to reduce CF triggers
CF_BACKOFF_MAX={{cf_backoff_max}}      # default 2700 = 45 min ceiling for CF preflight exponential backoff
MAX_CONSECUTIVE_FAILURES=${MAX_CONSECUTIVE_FAILURES:-5}  # halt after N back-to-back structural failures

# Heartbeat file: the entrypoint touches this before every significant sleep
# so the external watchdog can distinguish "alive, managing its own backoff"
# from "truly stuck."  Must be on the bind-mounted project dir so the host
# watchdog can stat it.
HEARTBEAT_FILE="{{project_dir}}/.dev-machine-heartbeat"

touch_heartbeat() {
    touch "$HEARTBEAT_FILE" 2>/dev/null || true
}

# -- Pre-flight: check if Anthropic API is reachable --------------------------
check_api() {
    # Minimal request to Anthropic API -- just enough to see if CF blocks us.
    # Uses the ANTHROPIC_API_KEY from env (loaded via env_file in compose).
    local api_key="${ANTHROPIC_API_KEY:-}"
    if [ -z "$api_key" ]; then
        echo "[preflight] No ANTHROPIC_API_KEY set, skipping check"
        return 0
    fi

    local response
    local http_code
    # Use the read-only models endpoint instead of POST /v1/messages.
    # A GET is lighter, costs nothing, and looks less bot-like to Cloudflare.
    # 200 = API reachable. 403 + HTML = Cloudflare challenge.
    http_code=$(curl -s -o /tmp/cf-check-body.txt -w '%{http_code}' \
        https://api.anthropic.com/v1/models \
        -H "x-api-key: $api_key" \
        -H "anthropic-version: 2023-06-01" \
        --connect-timeout 10 \
        --max-time 15 \
        2>/dev/null) || http_code="000"

    if [ "$http_code" = "403" ]; then
        # Check if it's actually Cloudflare (HTML body with "Just a moment")
        if grep -q "Just a moment" /tmp/cf-check-body.txt 2>/dev/null; then
            echo "[preflight] CLOUDFLARE CHALLENGE DETECTED (403 + managed challenge)"
            return 1
        fi
    fi

    if [ "$http_code" = "000" ]; then
        echo "[preflight] API unreachable (connection failed)"
        return 1
    fi

    if [ "$http_code" = "529" ] || [ "$http_code" = "503" ]; then
        echo "[preflight] API overloaded ($http_code)"
        return 1
    fi

    # 200 = success (unlikely with our minimal payload), 400 = bad request (expected),
    # 401 = bad key, 429 = rate limit -- all mean the API is reachable (not CF-blocked)
    echo "[preflight] API reachable (HTTP $http_code)"
    rm -f /tmp/cf-check-body.txt
    return 0
}

# -- Seed config files (first run with named volume) --------------------------
if [ -f /config/keys.env ] && [ ! -f "$AMPLIFIER_DIR/keys.env" ]; then
    cp /config/keys.env "$AMPLIFIER_DIR/keys.env"
    chmod 600 "$AMPLIFIER_DIR/keys.env"
fi

if [ -f /config/settings.yaml ] && [ ! -f "$AMPLIFIER_DIR/settings.yaml" ]; then
    cp /config/settings.yaml "$AMPLIFIER_DIR/settings.yaml"
fi

echo "Amplifier config ready at $AMPLIFIER_DIR"

# Source the keys.env so ANTHROPIC_API_KEY is available for pre-flight
if [ -f "$AMPLIFIER_DIR/keys.env" ]; then
    set -a
    source "$AMPLIFIER_DIR/keys.env" 2>/dev/null || true
    set +a
fi

# -- Install project dependencies if needed ------------------------------------
{{install_deps_block}}

# -- Run command with retry loop ----------------------------------------------
backoff=$INITIAL_BACKOFF
attempt=0
consecutive_structural_failures=0

while true; do
    attempt=$((attempt + 1))

    echo ""
    echo "=========================================="
    echo "  Dev Machine -- attempt $attempt"
    echo "  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "=========================================="
    echo ""

    # Pre-flight API check -- wait for Cloudflare to clear before launching.
    # Uses exponential backoff (15 min → 30 min → 45 min cap) so we make
    # fewer requests during long CF blocks, giving CF more time to forget us.
    touch_heartbeat
    cf_wait_count=0
    cf_current_backoff=$CF_BACKOFF
    while ! check_api; do
        cf_wait_count=$((cf_wait_count + 1))
        touch_heartbeat
        echo "[entrypoint] API not reachable. Waiting ${cf_current_backoff}s before retry... (preflight check $cf_wait_count)"
        sleep $cf_current_backoff
        # Exponential backoff: fewer requests = faster CF recovery
        cf_current_backoff=$((cf_current_backoff * 2))
        if [ $cf_current_backoff -gt $CF_BACKOFF_MAX ]; then
            cf_current_backoff=$CF_BACKOFF_MAX
        fi
    done

    if [ $cf_wait_count -gt 0 ]; then
        echo "[entrypoint] API reachable after $cf_wait_count preflight retries."
    fi

    start_time=$(date +%s)

    # Run the command; capture exit code and tee output for CF detection
    RECIPE_LOG="/tmp/recipe-output-$attempt.log"
    set +e
    "$@" 2>&1 | tee "$RECIPE_LOG"
    exit_code=${PIPESTATUS[0]}
    set -e

    end_time=$(date +%s)
    duration=$((end_time - start_time))

    # Check recipe output for mid-session Cloudflare challenge signature
    cf_mid_session=false
    if grep -q "Just a moment" "$RECIPE_LOG" 2>/dev/null; then
        cf_mid_session=true
        echo ""
        echo "[entrypoint] CLOUDFLARE CHALLENGE detected in recipe output (mid-session)."
    fi

    # Check if `amplifier tool invoke` reported an internal recipe failure.
    # The CLI exits 0 even when a recipe step fails with on_error=fail,
    # so we must inspect stdout.  Treat as a real error to avoid silent
    # 60-second loops that waste an entire night (the 514-attempt incident).
    recipe_internal_fail=false
    if [ $exit_code -eq 0 ] && grep -q "Recipe execution failed" "$RECIPE_LOG" 2>/dev/null; then
        recipe_internal_fail=true
        # Extract the failing step name for the log
        failing_step=$(grep -oP "Step '\K[^']+" "$RECIPE_LOG" 2>/dev/null | head -1)
        echo ""
        echo "[entrypoint] WARNING: recipe exited 0 but reported internal failure (step: ${failing_step:-unknown})."
        echo "[entrypoint] Treating as error to prevent silent loop."
        exit_code=1
    fi

    # Save tail before deleting -- used by post-mortem if we hit the failure cap
    last_log_lines=$(tail -20 "$RECIPE_LOG" 2>/dev/null || echo "(no log available)")
    rm -f "$RECIPE_LOG"

    # On success: loop back for next session (don't exit -- container stays alive)
    if [ $exit_code -eq 0 ]; then
        echo ""
        echo "[entrypoint] Recipe completed cleanly (code 0) after ${duration}s."
        echo "[entrypoint] Cooling down ${INTER_SESSION_COOLDOWN}s before next session..."
        echo ""
        backoff=$INITIAL_BACKOFF
        consecutive_structural_failures=0
        touch_heartbeat
        sleep $INTER_SESSION_COOLDOWN
        continue
    fi

    # If the run lasted long enough, it was making progress -- reset backoff
    if [ $duration -ge $SUCCESS_RESET ]; then
        backoff=$INITIAL_BACKOFF
        echo "[entrypoint] Run lasted ${duration}s (progress detected). Resetting backoff."
    fi

    # CF detected mid-session OR quick crash -- use extended backoff
    if [ "$cf_mid_session" = true ] || [ $duration -lt $CF_CRASH_THRESHOLD ]; then
        echo ""
        if [ "$cf_mid_session" = true ]; then
            echo "[entrypoint] Mid-session Cloudflare challenge confirmed."
        else
            echo "[entrypoint] QUICK CRASH (${duration}s < ${CF_CRASH_THRESHOLD}s threshold)."
            echo "[entrypoint] Likely Cloudflare challenge or API issue."
        fi
        echo "[entrypoint] Using extended backoff: ${CF_BACKOFF}s (attempt $attempt)"
        echo ""
        consecutive_structural_failures=0
        touch_heartbeat
        sleep $CF_BACKOFF
        # Don't increase backoff further -- CF_BACKOFF is already long
        continue
    fi

    echo ""
    echo "[entrypoint] Recipe exited with code $exit_code after ${duration}s."
    echo "[entrypoint] Retrying in ${backoff}s... (attempt $attempt)"
    echo ""

    touch_heartbeat
    sleep $backoff

    # Exponential backoff with cap
    backoff=$((backoff * 2))
    if [ $backoff -gt $MAX_BACKOFF ]; then
        backoff=$MAX_BACKOFF
    fi

    # -- Classify and track consecutive structural failures ----------------------
    # Structural = long-running failure (>= 60s) or explicit recipe_internal_fail.
    # Quick crashes that slipped past the CF filter are still treated as transient.
    if [ $duration -lt 60 ] && [ "$recipe_internal_fail" != "true" ]; then
        echo "[entrypoint] Quick crash (${duration}s < 60s) -- transient, structural counter unchanged (${consecutive_structural_failures}/${MAX_CONSECUTIVE_FAILURES})."
    else
        consecutive_structural_failures=$((consecutive_structural_failures + 1))
        echo "[entrypoint] Structural failure #${consecutive_structural_failures}/${MAX_CONSECUTIVE_FAILURES} (exit ${exit_code}, ${duration}s)."

        if [ $consecutive_structural_failures -ge $MAX_CONSECUTIVE_FAILURES ]; then
            echo ""
            echo "[entrypoint] CRITICAL: MAX_CONSECUTIVE_FAILURES ($MAX_CONSECUTIVE_FAILURES) reached. Halting retry loop."
            echo ""

            # Write a post-mortem file for human review
            POSTMORTEM_FILE="{{project_dir}}/.dev-machine-postmortem"
            {
                echo "=== Dev Machine Post-Mortem ==="
                echo "Date:                        $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
                echo "Consecutive structural failures: $consecutive_structural_failures / $MAX_CONSECUTIVE_FAILURES"
                echo "Last exit code:              $exit_code"
                echo "Last session duration:       ${duration}s"
                echo "Total attempts:              $attempt"
                echo ""
                echo "=== Last log lines ==="
                echo "$last_log_lines"
            } > "$POSTMORTEM_FILE"
            echo "[entrypoint] Post-mortem written to $POSTMORTEM_FILE"

            # Record STATE.yaml mtime so a human can resume by touching/modifying it
            STATE_FILE="{{project_dir}}/STATE.yaml"
            state_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")

            touch_heartbeat

            # Halt loop: keep the heartbeat alive every 5 minutes so the watchdog
            # knows this is an intentional pause, not a hang.
            # A human can resume by editing STATE.yaml (e.g. clearing a blocking task).
            echo "[entrypoint] Entering halt loop. Modify STATE.yaml or restart the container to resume."
            while true; do
                sleep 300
                touch_heartbeat
                new_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")
                if [ "$new_mtime" != "$state_mtime" ]; then
                    echo ""
                    echo "[entrypoint] STATE.yaml modified -- clearing halt, resuming retry loop."
                    echo ""
                    consecutive_structural_failures=0
                    break
                fi
                echo "[entrypoint] Still halted ($(date -u '+%H:%M:%S UTC')). Modify STATE.yaml to resume."
            done
        fi
    fi
done
