# =============================================================================
# Generated by amplifier-bundle-dev-machine — do not edit directly
# Amplifier Dev-Machine Container: {{project_name}}
#
# Sandboxed environment for autonomous AI agent execution.
# Agents have bash access but can only affect the bind-mounted project directory.
#
# Build:  docker compose -f docker-compose.dev-machine.yaml build
# Run:    docker compose -f docker-compose.dev-machine.yaml up -d
# Shell:  docker compose -f docker-compose.dev-machine.yaml exec dev-machine bash
#
# ---- Template variables ------------------------------------------------------
#
#   {{base_image}}           — Docker base image
#                              Python-primary: python:3.12-slim
#                              Node-primary:   node:22-bookworm-slim
#
#   {{user_uid}}             — Host user UID (bind-mount permission compatibility)
#   {{user_gid}}             — Host user GID (bind-mount permission compatibility)
#   {{username}}             — Host username; must equal $(basename {{user_home}})
#   {{user_home}}            — Absolute home path matching the HOST user's $HOME
#                              e.g. /home/samschillace
#                              MUST match host path — bind-mounts use this path
#
#   {{project_name}}         — Short project identifier, e.g. word4
#   {{project_dir}}          — Absolute path to project root
#                              e.g. /home/samschillace/dev/ANext/my-project
#
#   {{uv_version}}           — Pinned uv version, e.g. 0.10.4
#                              Never use :latest — version skew breaks lockfiles
#
#   {{system_packages}}      — Extra apt packages, space-separated (may be empty)
#                              Node base images need: python3 python3-pip python3-venv
#                              Compiled extensions need: build-essential
#
#   {{node_setup}}           — Multi-line Node.js setup block, or empty string
#                              For Python-primary projects that need Node (e.g. pyright):
#                                RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
#                                    && apt-get install -y --no-install-recommends nodejs \
#                                    && rm -rf /var/lib/apt/lists/*
#                              For Node base images or projects that don't need Node: leave empty
#
#   {{python_dev_tools}}     — uv tool install lines for Python dev tools, or empty
#                              Example: RUN uv tool install ruff && uv tool install pyright
#                              Leave empty for Node-primary projects without Python analysis
#
#   {{extra_pip_packages}}   — Additional system-python pip packages beyond pyyaml (may be empty)
#
#   {{install_command}}      — Project dependency install command, e.g.:
#                                pnpm install --frozen-lockfile
#                                uv sync --extra dev
#                              NOT used here — project source is bind-mounted at runtime,
#                              not available during docker build. Used in entrypoint.sh.
# =============================================================================

FROM {{base_image}}

# -- System dependencies -------------------------------------------------------
# git            — commits, branch ops, safe.directory config
# curl           — API pre-flight check in entrypoint; nodesource / apt key scripts
# ca-certificates — HTTPS for git+https Amplifier install and LLM API calls
# jq             — used in recipe bash steps for JSON parsing
# {{system_packages}} — project-specific extras; placed inline to avoid an
#                       orphaned backslash when the variable is empty
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        curl \
        ca-certificates \
        jq {{system_packages}} \
    && rm -rf /var/lib/apt/lists/*

# -- Node.js setup (optional) --------------------------------------------------
# Python-primary projects that need Node.js (e.g. for the pyright LSP server):
#   set {{node_setup}} to the nodesource install block shown in the header above.
# Node-primary projects (node:*-* base images): Node is already present,
#   leave {{node_setup}} empty — this section becomes a harmless blank line.
{{node_setup}}

# -- System Python: pyyaml + extras --------------------------------------------
# Recipe bash steps call `python3 -c "import yaml; ..."` to read/write STATE.yaml.
# pyyaml MUST live in system python3 — outside any project venv — so it is
# available unconditionally in every bash step, even before `uv sync` runs.
#
# --break-system-packages: required on Debian/Ubuntu base images (PEP 668
# "externally managed environment"). Harmless on official python:* images.
#
# Node base images: ensure python3-pip is included in {{system_packages}}.
# {{extra_pip_packages}} may be empty — trailing space on the install line is fine.
RUN python3 -m pip install --no-cache-dir --break-system-packages \
        pyyaml {{extra_pip_packages}}

# -- uv (pinned version) -------------------------------------------------------
# Copied directly from the official uv image — no curl|bash, no apt package.
# Pinned to {{uv_version}} to match the host and keep uv.lock compatible.
# Update intentionally when you want to upgrade; never set :latest.
COPY --from=ghcr.io/astral-sh/uv:{{uv_version}} /uv /uvx /usr/local/bin/

# -- Non-root user (UID/GID must match host for bind-mount permissions) --------
# Running as root causes permission issues: files written to the bind-mounted
# project directory become root-owned, blocking host-side cron monitors,
# `git status`, and any tooling that runs as the unprivileged host user.
#
# {{user_home}} MUST equal the host user's $HOME (e.g. /home/samschillace) so
# that bind-mounted paths (project dir, .ssh/known_hosts) resolve identically
# inside the container.  {{username}} must equal $(basename {{user_home}}).
ARG USER_UID={{user_uid}}
ARG USER_GID={{user_gid}}

RUN groupadd -g ${USER_GID} devmachine \
    && useradd -m -u ${USER_UID} -g ${USER_GID} -s /bin/bash \
         -d {{user_home}} {{username}}

# /config: staging area for read-only host secrets.  entrypoint.sh copies
# keys.env and settings.yaml from here into ~/.amplifier/ on first start,
# bridging the read-only /config volume into the writable named volume.
RUN mkdir -p /config \
    && chown ${USER_UID}:${USER_GID} /config

# Pre-create the project directory mount-point owned by the container user.
# Docker bind-mounts replace this at runtime, but pre-creating it user-owned
# prevents "permission denied" errors if the mount is absent or delayed.
RUN mkdir -p {{project_dir}} \
    && chown -R ${USER_UID}:${USER_GID} {{project_dir}}

# =============================================================================
# Everything below runs as the non-root container user
# =============================================================================
USER {{username}}

# uv tool binaries land in ~/.local/bin — must be on PATH before using them.
# Setting HOME explicitly guards against edge cases where it is not inherited.
ENV HOME={{user_home}}
ENV PATH="{{user_home}}/.local/bin:${PATH}"

# -- Amplifier CLI -------------------------------------------------------------
# Installed as the container user so the tool venv lives under ~/.local/share/uv/
# (not /root/), matching the PATH set above.
RUN uv tool install git+https://github.com/microsoft/amplifier

# -- Amplifier tool module dependencies ----------------------------------------
# tool-web and tool-mcp run inside Amplifier's own isolated uv tool venv, NOT
# in the project venv or system Python.  They must be installed explicitly into
# that venv by targeting its interpreter with --python.
#
#   tool-web requires: aiohttp (async HTTP), beautifulsoup4 (HTML parsing),
#                      ddgs (DuckDuckGo search), primp (TLS-fingerprint HTTP)
#   tool-mcp requires: mcp (Model Context Protocol client), pydantic (schemas)
RUN uv pip install \
        --python "{{user_home}}/.local/share/uv/tools/amplifier/bin/python" \
        aiohttp \
        beautifulsoup4 \
        "ddgs>=9.6.0" \
        "primp>=0.15.0,<1.0.0" \
        mcp \
        "pydantic>=2.0"

# -- Python dev tools (optional) -----------------------------------------------
# Set {{python_dev_tools}} to the install commands your project needs.
# Example: RUN uv tool install ruff && uv tool install pyright
# Leave empty for Node-primary projects or those without Python static analysis.
{{python_dev_tools}}

# -- Runtime directory structure -----------------------------------------------
# ~/.amplifier/projects — Amplifier session registry
# ~/.cache/uv           — uv package cache (persisted via named volume, avoids
#                         re-downloading on container restart)
# ~/.ssh                — must exist for known_hosts bind-mount to succeed
RUN mkdir -p \
        {{user_home}}/.amplifier/projects \
        {{user_home}}/.cache/uv \
        {{user_home}}/.ssh

# -- Git configuration ---------------------------------------------------------
# safe.directory — git refuses to operate in a directory owned by a different
#   UID without this.  Essential for bind-mounted project dirs where the host
#   UID and container UID differ even though the numeric values match.
# user.name/email — identity for commits authored by the dev machine inside
#   the container (recipe push steps use these).
# defaultBranch  — matches the project convention so `git init` produces "main".
RUN git config --global user.name  "Amplifier Dev Machine ({{project_name}})" \
    && git config --global user.email         "dev-machine@container.local" \
    && git config --global init.defaultBranch main \
    && git config --global --add safe.directory {{project_dir}}

# -- Entrypoint ----------------------------------------------------------------
# entrypoint.sh (generated from templates/scripts/entrypoint.sh) handles:
#   1. Seeding ~/.amplifier/ from the /config/ read-only volume on first start
#   2. Sourcing keys.env so ANTHROPIC_API_KEY is available for the pre-flight
#   3. Cloudflare-aware pre-flight: pings the Anthropic API before each attempt;
#      waits with exponential backoff if a CF managed challenge is detected
#   4. Retry loop with exponential backoff for normal errors; extended backoff
#      for quick crashes (< 120 s) or mid-session CF challenge signatures
#   5. Delegating to the amplifier recipe command passed as CMD / docker args
#
# Note on {{install_command}} (e.g. `uv sync --extra dev` or
# `pnpm install --frozen-lockfile`): this runs inside the build recipe at
# container startup, NOT here.  Project source is bind-mounted at runtime and
# is NOT present during `docker build`.
#
# COPY runs as root (Docker daemon) regardless of the USER instruction above.
# --chown ensures the file is owned by the container user, not root.
COPY --chown=${USER_UID}:${USER_GID} \
    .dev-machine/entrypoint.sh \
    {{user_home}}/entrypoint.sh

RUN chmod +x {{user_home}}/entrypoint.sh

# -- Working directory = project root ------------------------------------------
# Set last so earlier RUN steps don't accidentally create files here as root.
WORKDIR {{project_dir}}

ENTRYPOINT ["{{user_home}}/entrypoint.sh"]

# Default: execute the build recipe.  Override for one-off recipe runs:
#   docker compose run dev-machine \
#     amplifier tool invoke recipes operation=execute recipe_path=.dev-machine/fix-iteration.yaml
CMD ["amplifier", "tool", "invoke", "recipes", \
     "operation=execute", \
     "recipe_path=.dev-machine/build.yaml"]
